[package]
name = "cornix_web"
version = "0.1.0"
edition = "2024"

[dependencies]
cornix_logic = { path = "../cornix_logic" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
js-sys = "0.3.106"
wasm-bindgen = "0.2.129"
web-sys = { version = "0.3.106", features = ["Document", "Element", "Event", "EventTarget", "HtmlElement", "HtmlInputElement", "KeyboardEvent", "Navigator", "Node", "Window"] }

[lib]
crate-type = ["cdylib", "rlib"]
